# Generated by Django 2.2.5 on 2021-08-12 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='WaitingList',
        ),
    ]
